apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  namespace: shivangi
  labels:
    app: bms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
        - name: bms
          image: 81392756/bms:latest
          ports:
            - containerPort: 3000

